# Generated by Django 3.2.7 on 2021-09-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.ImageField(upload_to='')),
                ('notlar', models.TextField()),
                ('user', models.CharField(max_length=200)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
