# Generated by Django 3.2.7 on 2021-09-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotolar',
            name='dosya',
            field=models.ImageField(upload_to='dosyalar/'),
        ),
    ]
